# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e9bb7fd5f82ced5d0f85c4257f39dfc6c17def09daa34f0d09c6cd8ca9152bd87f193ce115384ce16a80c544cb80c98b6feebf4bc38aa7597579f0b8cf937ea

test:
  secret_key_base: d2c4473aaee9ef0300122f85284cb438c1270ecba2bac8a14e6a2d31f0ad9f48ef98d2aa6440abf23f9decbcfc0bbdd41e14372d07e0b829c13480dbf13fd45c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
